name: build

on:
  push:
    branches: [ dev, rel/* ]
    tags: [ '*' ]
  pull_request:
    branches: [ dev, rel/* ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: build-ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout submodule
      uses: actions/checkout@v3
      with:
        repository: openiddict/openiddict-core
        path: submodules/openiddict-core

    - name: Build documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: docfx.json

    - name: Publish website artifacts
      uses: actions/upload-artifact@v3
      with:
        name: website
        path: ./_site

  deploy-github-pages:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false && github.ref == 'refs/heads/dev'
    steps:
    - name: Download website
      uses: actions/download-artifact@v3
      with:
        name: website
        path: ./_site

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
        GIT_CONFIG_NAME: OpenIddict Bot
        GIT_CONFIG_EMAIL: 32257313+openiddict-bot@users.noreply.github.com
        COMMIT_MESSAGE: Update the documentation pages
