name: build

on:
  push:
    branches: [ dev, rel/* ]
    tags: [ '*' ]
  pull_request:
    branches: [ dev, rel/* ]

jobs:
  build:
    name: ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout submodule
      uses: actions/checkout@v2
      with:
        repository: openiddict/openiddict-core
        path: submodules/openiddict-core

    - name: Build documentation
      uses: nikeee/docfx-action@master
      with:
        args: docfx.json

    - name: Deploy to GitHub Pages
      if: ${{ github.repository_owner == 'openiddict' && (github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/rel/') || startsWith(github.ref, 'refs/tags/')) }}
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
        GIT_CONFIG_NAME: OpenIddict Bot
        GIT_CONFIG_EMAIL: 32257313+openiddict-bot@users.noreply.github.com
        COMMIT_MESSAGE: Update the documentation pages
