name: push

on:
  push:
    branches:
      - dev

jobs:
  sponsor_job:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Generate sponsors section
      uses: JamesIves/github-sponsors-readme-action@02650b8cd445fc16dfef73195f9c406dce041623 # v1.6.1
      with:
        token: ${{ secrets.SPONSORS_TOKEN }}
        file: 'index.md'

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
      with:
        branch: dev
        folder: '.'
        token: ${{ secrets.GITHUB_TOKEN }}
        git-config-name: OpenIddict Bot
        git-config-email: 32257313+openiddict-bot@users.noreply.github.com
        commit-message: Update the sponsors section